---
- name: Instantiate VMs
  gather_facts: no
  become: true
  hosts: localhost
  vars_files:
    - ../misc/ws_auth.yaml
    - ../misc/db_auth.yaml
    - ../misc/client_auth.yaml
  tasks:
    - name: Install pyone
      ansible.builtin.pip:
        name: pyone==6.10.0 # crashes without version
        state: present

    - name: Instantiate webserver templated VM
      community.general.one_vm:
        api_url: https://grid5.mif.vu.lt/cloud3/RPC2
        api_username: "{{ ws_user }}"
        api_password: "{{ ws_password }}"
        template_id: 2730
        disk_size: 8 GB
        attributes:
          name: webserver-vm
        state: present
      register: webres

    - debug:
        msg: "Webserver IP: {{ webres.instances[0].networks[0].ip }}"

    - name: Instantiate database templated VM
      community.general.one_vm:
        api_url: https://grid5.mif.vu.lt/cloud3/RPC2
        api_username: "{{ db_user }}"
        api_password: "{{ db_password }}"
        template_id: 1737
        disk_size: 10 GB
        attributes:
          name: db-vm
        state: present
      register: dbres

    - debug:
        msg: "Database IP: {{ dbres.instances[0].networks[0].ip }}"

    - name: Instantiate client templated VM
      community.general.one_vm:
        api_url: https://grid5.mif.vu.lt/cloud3/RPC2
        api_username: "{{ client_user }}"
        api_password: "{{ client_password }}"
        template_id: 2646
        disk_size: 8 GB
        memory: 1024 MB
        attributes:
          name: client-vm
        state: present
      register: clientres

    - debug:
        msg: "Client IP: {{ clientres.instances[0].networks[0].ip }}"

    - name: Insert private ips into ansible hosts file
      ansible.builtin.blockinfile:
        path: /etc/ansible/hosts
        block: |
          [webserver]
          {{ webres.instances[0].networks[0].ip }}

          [db]
          {{ dbres.instances[0].networks[0].ip }}

          [client]
          {{ clientres.instances[0].networks[0].ip }}

        create: yes
        insertafter: EOF
