---
- name: Instantiate VMs
  gather_facts: no
  hosts: localhost
  tasks:
    - name: Install pyone
      ansible.builtin.pip:
        name: pyone==6.10.0 # crashes without version 
        state: present
    - name: Instantiate webserver templated VM
      community.general.one_vm:
        api_url: https://grid5.mif.vu.lt/cloud3/RPC2
        template_id: 1737
        disk_size: 8 GB
        memory: 1024 MB
        attributes:
          name: webserver-vm
        state: present
      register: webres

    - debug:
        msg: "Webserver IP: {{ webres.instances[0].networks[0].ip }}"

    - name: Insert private ips into ansible hosts file
      ansible.builtin.blockinfile:
        path: /etc/ansible/hosts
        block: |
          [webserver]
          {{ webres.instances[0].networks[0].ip }}

          [db]
          

          [client]
        
        create: yes
        insertafter: EOF