---
- name: Instantiate VMs
  gather_facts: no
  become: true
  hosts: localhost
  tasks:
    - name: Install pyone
      ansible.builtin.pip:
        name: pyone==6.10.0 # crashes without version 
        state: present
        
    - name: Instantiate client templated VM
      community.general.one_vm:
        api_url: https://grid5.mif.vu.lt/cloud3/RPC2
        template_id: 2646
        attributes:
          name: client-vm
        state: present
      environment:
        ONE_AUTH: /root/auth/client_auth
      register: clientres

    - debug:
        msg: "Client IP: {{ clientres.instances[0].networks[0].ip }}"

    - name: Insert private ips into ansible hosts file
      ansible.builtin.blockinfile:
        path: /etc/ansible/hosts
        block: |
          [client]
          {{ clientres.instances[0].networks[0].ip }}

        create: yes
        insertafter: EOF
