---
- name: Configure webserver VM
  gather_facts: no
  become: yes
  hosts: webserver
  tasks:
    - name: create lock dir
      file:
        path: /var/lib/apt/lists
        state: directory

    - name: update
      apt:
        update_cache: yes

    - name: upgrade
      apt:
        upgrade: true
  
    - name: Install prerequisites for Docker
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes
    
    - name: Create Docker keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
        filename: docker
    
    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      
    - name: Ensure Docker runs
      systemd:
        name: docker
        state: started
        enabled: yes
    
    
